openapi: 3.0.0
info:
    title: SolveOS Authentication API
    description: FastAPI OAuth2 password flow authentication for SolveOS
    version: 1.0.0
    contact:
        name: SolveOS Team
servers:
    - url: http://localhost:8000
      description: Development server
paths:
    /api/auth/token:
        post:
            summary: Login
            description: Authenticates a user using OAuth2 password flow and returns an access token
            operationId: login
            tags:
                - Authentication
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequest'
            responses:
                '200':
                    description: Successful authentication
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponse'
                '401':
                    description: Invalid credentials
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '422':
                    description: Validation error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ValidationError'
components:
    schemas:
        LoginRequest:
            type: object
            required:
                - username
                - password
            properties:
                username:
                    type: string
                    format: email
                    description: User's email address
                    example: user@example.com
                password:
                    type: string
                    format: password
                    description: User's password
                    example: password123
                grant_type:
                    type: string
                    default: password
                    description: OAuth2 grant type
                    example: password
                scope:
                    type: string
                    description: OAuth2 scope (optional)
                    example: ''
                client_id:
                    type: string
                    description: OAuth2 client ID (optional)
                client_secret:
                    type: string
                    description: OAuth2 client secret (optional)
        LoginResponse:
            type: object
            required:
                - access_token
                - token_type
            properties:
                access_token:
                    type: string
                    description: JWT access token
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                token_type:
                    type: string
                    description: Token type
                    example: bearer
                refresh_token:
                    type: string
                    description: Refresh token for obtaining new access tokens (optional)
                    example: refresh_token_here
                expires_in:
                    type: integer
                    description: Token expiration time in seconds
                    example: 1800
                user:
                    $ref: '#/components/schemas/User'
        User:
            type: object
            required:
                - id
                - email
            properties:
                id:
                    type: string
                    description: Unique user identifier
                    example: 123e4567-e89b-12d3-a456-426614174000
                email:
                    type: string
                    format: email
                    description: User's email address
                    example: user@example.com
                name:
                    type: string
                    description: User's full name
                    example: John Doe
                first_name:
                    type: string
                    description: User's first name
                    example: John
                last_name:
                    type: string
                    description: User's last name
                    example: Doe
                role:
                    type: string
                    description: User's role or permission level
                    example: user
                is_verified:
                    type: boolean
                    description: Whether the user's email is verified
                    example: true
                is_active:
                    type: boolean
                    description: Whether the user account is active
                    example: true
                created_at:
                    type: string
                    format: date-time
                    description: Timestamp of user creation
                    example: '2025-10-19T10:30:00Z'
        Error:
            type: object
            required:
                - detail
            properties:
                detail:
                    type: string
                    description: Error message
                    example: Incorrect email or password
        ValidationError:
            type: object
            properties:
                detail:
                    type: array
                    items:
                        type: object
                        properties:
                            loc:
                                type: array
                                items:
                                    type: string
                                description: Location of the error
                            msg:
                                type: string
                                description: Error message
                            type:
                                type: string
                                description: Error type
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: JWT token obtained from /api/auth/token endpoint
tags:
    - name: Authentication
      description: User authentication endpoints
